- name: Quita el par√°metro pnpacpi=off de /etc/default/grub
  replace:
    dest: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT="quiet splash pnpacpi=off"'
    replace: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"'
  notify:
    - update-grub
