---

- name: Pone el par√°metro pnpacpi=off en /etc/default/grub
  replace:
    dest: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"'
    replace: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet splash pnpacpi=off"'
  notify:
    - update-grub
